version: '3.3'
services:
  web-service:
    depends_on:
      - model-service
    image: bonsli/djl-webapp-luccinic:latest
    ports:
      - "80:8082"
    restart: always
  model-service:
    image: bonsli/djl-serving-luccinic:latest
    restart: always